version: "3"
services:
    sql_server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=zr%uN&pqLq6G
        ports:
            - "1433:1433"
